prometheus:
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true
  server:
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 800Mi
        cpu: 400m
    extraScrapeConfigs:
      - job_name: "nodejs-app"
        static_configs:
          - targets: ["hello-si-devops:3000"] # Replace with your app's service name and port

grafana:
  adminPassword: "admin"
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m

apiVersion: v1
kind: Service
metadata:
  name: hello-si-devops
  namespace: default
spec:
  selector:
    app: hello-si-devops
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # App's container port
  type: ClusterIP # Use ClusterIP for internal communication
