apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-si-devops-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: hello-si-devops
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default