apiVersion: v1
kind: Service
metadata:
  name: hello-si-devops-metrics # This is the name Prometheus is trying to scrape
  namespace: default
spec:
  selector:
    app: hello-si-devops
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
